# DBT Project Configuration
# https://docs.getdbt.com/reference/dbt_project.yml

name: 'lakehouse_analytics'
version: '2.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'lakehouse'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  lakehouse_analytics:
    # ========================================================================
    # Single Namespace: All tables in 'data' schema
    # ========================================================================
    # Organization via table prefixes:
    #   - Source tables: payment_events, payment_events_quarantine
    #   - Intermediate: int_payment_customer_metrics, int_payment_merchant_metrics
    #   - Marts: dim_customer, dim_merchant, dim_date, fct_payments, fct_daily_payments

    # Staging Layer: Source-conformed atomic building blocks
    # Schema inherited from profile (data)
    staging:
      +materialized: view
      +tags: ["staging"]
      payments:
        +materialized: incremental
        +incremental_strategy: merge
        +tags: ["staging", "payments"]

    # Intermediate Layer: Purpose-built transformations
    intermediate:
      +materialized: ephemeral
      +tags: ["intermediate"]
      payments:
        +tags: ["intermediate", "payments"]

    # Marts Layer: Business-conformed entities
    marts:
      +tags: ["marts"]
      payments:
        +materialized: incremental
        +incremental_strategy: merge
        +tags: ["marts", "payments"]

    # Analytics Layer: Superset-optimized aggregations
    analytics:
      +materialized: table
      +tags: ["analytics"]
      payments:
        +tags: ["analytics", "payments"]

# Seeds configuration (CSV files loaded as tables)
seeds:
  lakehouse_analytics:
    +schema: seeds
    +tags: ["seeds"]

# Snapshot configuration (SCD Type 2 tracking)
snapshots:
  lakehouse_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
    +tags: ["snapshots", "scd"]

# Variables
vars:
  # Date range for incremental models
  start_date: '2024-01-01'

  # Surrogate key generation
  surrogate_key_treat_nulls_as_empty_strings: true
