# ============================================================================
# DBT Sources Configuration - Payment Data
# ============================================================================
# This file defines payment data sources ingested by Dagster from PostgreSQL.
# Data is stored in MinIO S3 as Iceberg tables via the dagster-iceberg IO manager.
#
# Data Flow:
#   Stripe Webhook -> Gateway -> Kafka -> Normalizer -> Temporal Orchestrator
#   -> PostgreSQL -> Dagster -> Iceberg (this source)
#
# Documentation: https://docs.getdbt.com/docs/building-a-dbt-project/using-sources
# ============================================================================

version: 2

sources:
  # ============================================================================
  # Payment Events - Bronze Layer (From PostgreSQL via Dagster)
  # ============================================================================
  - name: bronze_payments
    description: "Enriched payment events ingested from PostgreSQL by Dagster"
    database: iceberg
    schema: data

    # Freshness checks - batch ingestion runs every 15 minutes
    freshness:
      warn_after: {count: 30, period: minute}
      error_after: {count: 60, period: minute}
    loaded_at_field: "ingested_at"

    tables:
      # Main payment events table (from PostgreSQL payment_events)
      - name: payment_events
        description: |
          Enriched payment events from Temporal workflows.
          Includes ML inference results (fraud score, churn prediction, retry strategy).
          Ingested by Dagster from PostgreSQL bronze layer.
        columns:
          - name: event_id
            description: "Unique event identifier (provider:original_id format)"
            tests:
              - unique
              - not_null
          - name: provider
            description: "Payment provider (stripe, square, etc.)"
            tests:
              - not_null
              - accepted_values:
                  values: ['stripe', 'square', 'paypal', 'adyen']
          - name: provider_event_id
            description: "Original event ID from the provider"
          - name: event_type
            description: "Normalized event type (payment.succeeded, payment.failed, etc.)"
            tests:
              - not_null
          - name: merchant_id
            description: "Merchant identifier"
          - name: customer_id
            description: "Customer identifier"
          - name: amount_cents
            description: "Transaction amount in cents"
          - name: currency
            description: "ISO 4217 currency code"
            tests:
              - accepted_values:
                  values: ['USD', 'EUR', 'GBP', 'CAD', 'AUD', 'JPY', 'CHF', 'CNY', 'INR', 'MXN',
                          'BRL', 'KRW', 'SGD', 'HKD', 'NOK', 'SEK', 'DKK', 'NZD', 'ZAR', 'PLN']
          - name: payment_method_type
            description: "Payment method type (card, bank_transfer, etc.)"
          - name: card_brand
            description: "Card brand (visa, mastercard, amex, etc.)"
          - name: card_last_four
            description: "Last 4 digits of card"
          - name: status
            description: "Payment status (succeeded, failed, pending, etc.)"
            tests:
              - not_null
          - name: failure_code
            description: "Failure code for failed payments"
          - name: failure_message
            description: "Failure message for failed payments"

          # ML Enrichment Fields
          - name: fraud_score
            description: "Fraud probability score (0-1) from inference service"
          - name: risk_level
            description: "Risk level classification (low, medium, high)"
          - name: retry_strategy
            description: "Recommended retry strategy for failed payments"
          - name: retry_delay_seconds
            description: "Recommended delay before retry"
          - name: churn_score
            description: "Customer churn probability score (0-1)"
          - name: churn_risk_level
            description: "Churn risk classification (low, medium, high)"
          - name: days_to_churn_estimate
            description: "Estimated days until customer churns"

          # Validation Fields
          - name: validation_status
            description: "Validation status (passed, failed)"
          - name: validation_errors
            description: "JSON array of validation errors"

          # Timestamps
          - name: provider_created_at
            description: "When the provider created the event"
          - name: processed_at
            description: "When Temporal processed the event"
          - name: ingested_at
            description: "When Dagster ingested to Iceberg"
            tests:
              - not_null

          # Metadata
          - name: metadata
            description: "Provider-specific metadata (JSON)"
          - name: schema_version
            description: "Schema version for evolution tracking"

      # Quarantine table for failed/invalid events
      # Note: Table created by Dagster when quarantine events exist
      - name: payment_events_quarantine
        description: |
          Quarantined payment events that failed validation.
          Contains original payload for manual review and reprocessing.
        config:
          enabled: false  # Table may not exist until quarantine events occur
        columns:
          - name: event_id
            description: "Event identifier"
            tests:
              - not_null
          - name: provider
            description: "Payment provider"
          - name: provider_event_id
            description: "Original provider event ID"
          - name: original_payload
            description: "Full original event payload (JSON)"
            tests:
              - not_null
          - name: validation_errors
            description: "JSON array of validation errors"
          - name: failure_reason
            description: "Why the event was quarantined"
          - name: source_topic
            description: "Kafka topic the event came from"
          - name: kafka_partition
            description: "Kafka partition"
          - name: kafka_offset
            description: "Kafka offset"
          - name: quarantined_at
            description: "When the event was quarantined"
            tests:
              - not_null
          - name: reviewed
            description: "Whether the event has been reviewed"
          - name: reviewed_at
            description: "When the event was reviewed"
          - name: reviewed_by
            description: "Who reviewed the event"
          - name: resolution
            description: "Resolution (reprocessed, discarded, manual_fix)"
          - name: schema_version
            description: "Schema version"
