# DBT Profiles Configuration
# https://docs.getdbt.com/reference/profiles.yml

# This file configures database connections for DBT
# In production, use environment variables for sensitive credentials

lakehouse:
  target: dev
  outputs:
    dev:
      type: trino
      method: none  # No authentication for local development
      user: dbt_user  # Required by dbt-trino adapter
      host: "{{ env_var('TRINO_HOST', 'trino') }}"  # Docker: trino, local: localhost with port-forward
      port: 8080
      database: iceberg  # Trino catalog name (connected to Polaris)
      schema: data  # Namespace where Iceberg tables are stored
      threads: 2
      http_scheme: http
      session_properties:
        query_max_run_time: 4h
        query_max_memory: 512MB

    prod:
      type: trino
      method: none
      user: dbt_user  # Required by dbt-trino adapter
      host: trino  # Kubernetes service DNS (same namespace)
      port: 8080
      database: iceberg  # Trino catalog name (connected to Polaris)
      schema: data  # Namespace where Iceberg tables are stored
      threads: 8
      http_scheme: http
      session_properties:
        query_max_run_time: 8h
        query_result_cache_enabled: true

# Database connects to Trino's Iceberg catalog
# Port-forward for local dev: kubectl port-forward svc/trino 8080:8080 -n lakehouse
