# DBT Project Configuration
# https://docs.getdbt.com/reference/dbt_project.yml

name: 'lakehouse_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'lakehouse'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  lakehouse_analytics:
    # Bronze layer: Raw data staging models
    # Materialized as views for efficient querying of latest data
    bronze:
      +materialized: view
      +schema: bronze
      +tags: ["bronze", "staging"]

    # Silver layer: Cleaned and conformed dimension tables
    # Materialized as incremental tables for efficient updates
    # Uses Iceberg format for ACID transactions and time travel
    silver:
      +materialized: incremental
      +schema: silver
      +file_format: iceberg
      +incremental_strategy: merge
      +tags: ["silver", "dimensions"]

    # Gold layer: Business-ready fact tables and aggregates
    # Materialized as incremental tables optimized for analytics
    gold:
      +materialized: incremental
      +schema: gold
      +file_format: iceberg
      +incremental_strategy: merge
      +tags: ["gold", "facts", "analytics"]

# Seeds configuration (CSV files loaded as tables)
seeds:
  lakehouse_analytics:
    +schema: seeds
    +tags: ["seeds"]

# Snapshot configuration (SCD Type 2 tracking)
snapshots:
  lakehouse_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
    +tags: ["snapshots", "scd"]

# Variables
vars:
  # Date range for incremental models
  start_date: '2024-01-01'

  # Surrogate key generation
  surrogate_key_treat_nulls_as_empty_strings: true
