# DBT Project Configuration
# https://docs.getdbt.com/reference/dbt_project.yml

name: 'lakehouse_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'lakehouse'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  lakehouse_analytics:
    # ========================================================================
    # Staging Layer: Source-conformed atomic building blocks
    # ========================================================================
    # Materialized as views (no storage overhead)
    # Basic type casting, cleaning, unions
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
      reddit:
        +tags: ["staging", "reddit"]

    # ========================================================================
    # Intermediate Layer: Purpose-built transformations
    # ========================================================================
    # Materialized as ephemeral (not persisted, used as CTEs)
    # Aggregations, calculations, enrichments
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
      +tags: ["intermediate"]
      reddit:
        +tags: ["intermediate", "reddit"]

    # ========================================================================
    # Marts Layer: Business-conformed entities
    # ========================================================================
    # Dimensions and facts with surrogate keys
    # Incremental Iceberg tables for efficient updates
    marts:
      +schema: marts
      +tags: ["marts"]
      reddit:
        +materialized: incremental
        +file_format: iceberg
        +incremental_strategy: merge
        +tags: ["marts", "reddit"]

    # ========================================================================
    # DEPRECATED: Old bronze/silver/gold structure
    # ========================================================================
    # Kept for reference, to be removed after migration
    bronze:
      +materialized: view
      +schema: bronze
      +tags: ["bronze", "staging", "deprecated"]

    silver:
      +materialized: incremental
      +schema: silver
      +file_format: iceberg
      +incremental_strategy: merge
      +tags: ["silver", "dimensions", "deprecated"]

    gold:
      +materialized: incremental
      +schema: gold
      +file_format: iceberg
      +incremental_strategy: merge
      +tags: ["gold", "facts", "analytics", "deprecated"]

# Seeds configuration (CSV files loaded as tables)
seeds:
  lakehouse_analytics:
    +schema: seeds
    +tags: ["seeds"]

# Snapshot configuration (SCD Type 2 tracking)
snapshots:
  lakehouse_analytics:
    +target_schema: snapshots
    +strategy: timestamp
    +updated_at: updated_at
    +tags: ["snapshots", "scd"]

# Variables
vars:
  # Date range for incremental models
  start_date: '2024-01-01'

  # Surrogate key generation
  surrogate_key_treat_nulls_as_empty_strings: true
