# PyIceberg configuration for Polaris REST catalog
# This configures how DLT writes Iceberg tables with table_format="iceberg"

catalog:
  lakehouse:
    type: rest
    uri: http://localhost:8181/api/catalog
    credential: polaris_admin:polaris_admin_secret
    warehouse: lakehouse
    # S3 configuration for MinIO storage
    s3.endpoint: http://localhost:9000
    s3.access-key-id: admin
    s3.secret-access-key: minio123
    s3.path-style-access: true
    s3.region: us-east-1
