# ============================================================================
# DBT Sources Configuration - TEMPLATE
# ============================================================================
# STATUS: Template - REQUIRES CONFIGURATION
#
# This file defines the raw data sources that DBT will read from.
# Update this file once you have:
#   1. Configured Airbyte data source connections
#   2. Run initial data ingestion
#   3. Verified raw Iceberg tables are created
#
# Documentation: https://docs.getdbt.com/docs/building-a-dbt-project/using-sources
# ============================================================================

version: 2

sources:
  # Raw data source from Airbyte ingestion
  - name: raw
    description: "Raw data ingested by Airbyte into Iceberg tables"
    database: lakehouse
    schema: bronze

    # Freshness checks - ensure data is being ingested regularly
    # Uncomment and configure once data ingestion is active
    # freshness:
    #   warn_after: {count: 24, period: hour}
    #   error_after: {count: 48, period: hour}

    # Configure loaded_at_field for freshness checks
    # This should be an Airbyte metadata column
    # loaded_at_field: _airbyte_emitted_at

    tables:
      # ============================================================================
      # EXAMPLE SOURCE TABLES - Update with actual table names from Airbyte
      # ============================================================================

      - name: customers
        description: "Raw customer data from source system"
        # TODO: Update table name to match actual Airbyte destination table
        # Example: raw_customers, raw_mysql_customers, etc.

        # Uncomment to add column documentation and tests
        # columns:
        #   - name: customer_id
        #     description: "Unique customer identifier"
        #     tests:
        #       - unique
        #       - not_null
        #   - name: email
        #     description: "Customer email address"
        #     tests:
        #       - not_null
        #   - name: _airbyte_emitted_at
        #     description: "Timestamp when Airbyte emitted this record"

      - name: orders
        description: "Raw order transaction data"
        # TODO: Update table name to match actual Airbyte destination table

        # columns:
        #   - name: order_id
        #     description: "Unique order identifier"
        #     tests:
        #       - unique
        #       - not_null
        #   - name: customer_id
        #     description: "Foreign key to customer"
        #     tests:
        #       - not_null
        #   - name: order_date
        #     description: "Date order was placed"
        #     tests:
        #       - not_null

      - name: products
        description: "Raw product catalog data"
        # TODO: Update table name to match actual Airbyte destination table

        # columns:
        #   - name: product_id
        #     description: "Unique product identifier"
        #     tests:
        #       - unique
        #       - not_null
        #   - name: product_name
        #     description: "Product name"
        #     tests:
        #       - not_null

# ============================================================================
# How to Configure This File
# ============================================================================
#
# 1. Deploy Airbyte and configure source connections
#    - See: infrastructure/kubernetes/airbyte/
#
# 2. Identify the raw table names created by Airbyte
#    - Connect to Trino: kubectl port-forward svc/trino 8080:8080 -n trino
#    - Query: SHOW TABLES IN lakehouse.bronze;
#
# 3. Update the table names in this file
#    - Replace 'customers' with actual table name (e.g., 'raw_customers')
#    - Add/remove tables as needed for your data sources
#
# 4. Configure column tests and documentation
#    - Uncomment the columns section
#    - Add descriptions and tests for each important column
#
# 5. Enable freshness checks
#    - Uncomment the freshness configuration
#    - Set appropriate warning/error thresholds
#
# 6. Test your sources
#    - Run: dbt source freshness
#    - Run: dbt test --select source:*
#
# ============================================================================
